sudo: required

services:
  - docker

before_install:
  - env | sort
  - docker pull obolibrary/odkfull

before_script:
  - cd src/ontology

script:
  - env | sort
  - curl -X POST "https://monarch-jenkins.cgrb.oregonstate.edu/job/test-mondo/build" -H "Jenkins-Crumb:${ShahimCSRFCrumb}" --user essaids:${ShahimAPIToken} --form json='{"parameter": [{"name":"Hello", "value":"WorlParameterValue2"}]}
  - ./run.sh make monarch-jenkins

# whitelist
branches:
  only:
    - master
    - test-travis
    - jenkins-setup

### UNCOMMENT THIS AND ADD YOUR DETAILS:
#notifications:
#  email:
#    - YOURNAME@YOU.ORG
