sudo: required

services:
  - docker

before_install:
  - env
  - docker pull obolibrary/odkfull

before_script:
  - cd src/ontology

script:
  - env
  - ./run.sh make monarch-jenkins

# whitelist
branches:
  only:
    - master
    - test-travis
    - jenkins-setup

### UNCOMMENT THIS AND ADD YOUR DETAILS:
#notifications:
#  email:
#    - YOURNAME@YOU.ORG
